print_freq: 50
output_dir: './logs'
checkpoint_freq: 2


sync_bn: True
find_unused_parameters: True


use_amp: True
scaler:
  type: GradScaler
  enabled: True


use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
